### ISSUE TITLE
t/api/reverse-dependencies.t started to fail

### ISSUE THREAD

**Issue by eserte** [metacpan/metacpan-client#118]
I see the following new failure on my smokers:
```
#   Failed test 'CPANSec::Admin is a valid reverse dependency'
#   at t/api/reverse-dependencies.t line 40.
#          got: undef
#     expected: '1'
# Looks like you failed 1 test of 60.
t/api/reverse-dependencies.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/60 subtests 
```

Possibly the problem started a few days ago: http://matrix.cpantesters.org/?dist=MetaCPAN-Client%202.030000;reports=1#sl=7,1

**Comment by oalders** [comment]
Thanks for this, @eserte!

**Comment by mickeyn** [comment]
@eserte Thanks for reporting.

I've seen it through IRC and checked it - this is a mismatch of dist and module name on the release of CPANSec::Admin  (should be CPANSEC::Admin) which depends on MetaCPAN::Client.
Nothing for us to do on this side, it's just a coincidence that we caught this one because the test (which is for the resverse_dependencies endpoint of MetaCPAN API) could have randomly checked against any other package and expose any other issue on the releases side.
